// Type Imports
import type { UsersType } from '@/types/apps/userTypes'

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const db: UsersType[] = ([
  {
    id: 1,
    fullName: 'Galen Slixby',
    role: 'editor',
    username: 'gslixby0',
    contact: '(479) 232-9151',
    email: 'gslixby0@abc.net.au',
    status: 'inactive',
  },
  {
    id: 2,
    fullName: 'Halsey Redmore',
    role: 'author',
    username: 'hredmore1',
    contact: '(472) 607-9137',
    email: 'hredmore1@imgur.com',
    status: 'pending',
  },
  {
    id: 3,
    fullName: 'Marjory Sicely',
    role: 'maintainer',
    username: 'msicely2',
    contact: '(321) 264-4599',
    email: 'msicely2@who.int',
    status: 'active',
  },
  {
    id: 4,
    fullName: 'Cyrill Risby',
    role: 'maintainer',
    username: 'crisby3',
    contact: '(923) 690-6806',
    email: 'crisby3@wordpress.com',
    status: 'inactive',
  },
  {
    id: 5,
    fullName: 'Maggy Hurran',
    role: 'user',
    username: 'mhurran4',
    contact: '(669) 914-1078',
    email: 'mhurran4@yahoo.co.jp',
    status: 'pending',
  },
  {
    id: 6,
    fullName: 'Silvain Halstead',
    role: 'author',
    username: 'shalstead5',
    contact: '(958) 973-3093',
    email: 'shalstead5@shinystat.com',
    status: 'active',
  },
  {
    id: 7,
    fullName: 'Breena Gallemore',
    role: 'user',
    username: 'bgallemore6',
    contact: '(825) 977-8152',
    email: 'bgallemore6@boston.com',
    status: 'pending',
  },
  {
    id: 8,
    fullName: 'Kathryne Liger',
    role: 'author',
    username: 'kliger7',
    contact: '(187) 440-0934',
    email: 'kliger7@vinaora.com',
    status: 'pending',
  },
  {
    id: 9,
    fullName: 'Franz Scotfurth',
    role: 'user',
    username: 'fscotfurth8',
    contact: '(978) 146-5443',
    email: 'fscotfurth8@dailymotion.com',
    status: 'pending',
  },
  {
    id: 10,
    fullName: 'Jillene Bellany',
    role: 'maintainer',
    username: 'jbellany9',
    contact: '(589) 284-6732',
    email: 'jbellany9@kickstarter.com',
    status: 'inactive',
  },
  {
    id: 11,
    fullName: 'Jonah Wharlton',
    role: 'user',
    username: 'jwharltona',
    contact: '(176) 532-6824',
    email: 'jwharltona@oakley.com',
    status: 'inactive',
  },
  {
    id: 12,
    fullName: 'Seth Hallam',
    role: 'user',
    username: 'shallamb',
    contact: '(234) 464-0600',
    email: 'shallamb@hugedomains.com',
    status: 'pending',
  },
  {
    id: 13,
    fullName: 'Yoko Pottie',
    role: 'user',
    username: 'ypottiec',
    contact: '(907) 284-5083',
    email: 'ypottiec@privacy.gov.au',
    status: 'inactive',
  },
  {
    id: 14,
    fullName: 'Maximilianus Krause',
    role: 'author',
    username: 'mkraused',
    contact: '(167) 135-7392',
    email: 'mkraused@stanford.edu',
    status: 'active',
  },
  {
    id: 15,
    fullName: 'Zsazsa McCleverty',
    role: 'maintainer',
    username: 'zmcclevertye',
    contact: '(317) 409-6565',
    email: 'zmcclevertye@soundcloud.com',
    status: 'active',
  },
  {
    id: 16,
    fullName: 'Bentlee Emblin',
    role: 'author',
    username: 'bemblinf',
    contact: '(590) 606-1056',
    email: 'bemblinf@wired.com',
    status: 'active',
  },
  {
    id: 17,
    fullName: 'Brockie Myles',
    role: 'maintainer',
    username: 'bmylesg',
    contact: '(553) 225-9905',
    email: 'bmylesg@amazon.com',
    status: 'active',
  },
  {
    id: 18,
    fullName: 'Bertha Biner',
    role: 'editor',
    username: 'bbinerh',
    contact: '(901) 916-9287',
    email: 'bbinerh@mozilla.com',
    status: 'active',
  },
  {
    id: 19,
    fullName: 'Travus Bruntjen',
    role: 'admin',
    username: 'tbruntjeni',
    contact: '(524) 586-6057',
    email: 'tbruntjeni@sitemeter.com',
    status: 'active',
  },
  {
    id: 20,
    fullName: 'Wesley Burland',
    role: 'editor',
    username: 'wburlandj',
    contact: '(569) 683-1292',
    email: 'wburlandj@uiuc.edu',
    status: 'inactive',
  },
  {
    id: 21,
    fullName: 'Selina Kyle',
    role: 'admin',
    username: 'catwomen1940',
    contact: '(829) 537-0057',
    email: 'irena.dubrovna@wayne.com',
    status: 'active',
  },
  {
    id: 22,
    fullName: 'Jameson Lyster',
    role: 'editor',
    username: 'jlysterl',
    contact: '(593) 624-0222',
    email: 'jlysterl@guardian.co.uk',
    status: 'inactive',
  },
  {
    id: 23,
    fullName: 'Kare Skitterel',
    role: 'maintainer',
    username: 'kskitterelm',
    contact: '(254) 845-4107',
    email: 'kskitterelm@ainyx.com',
    status: 'pending',
  },
  {
    id: 24,
    fullName: 'Cleavland Hatherleigh',
    role: 'admin',
    username: 'chatherleighn',
    contact: '(700) 783-7498',
    email: 'chatherleighn@washington.edu',
    status: 'pending',
  },
  {
    id: 25,
    fullName: 'Adeline Micco',
    role: 'admin',
    username: 'amiccoo',
    contact: '(227) 598-1841',
    email: 'amiccoo@whitehouse.gov',
    status: 'pending',
  },
  {
    id: 26,
    fullName: 'Hugh Hasson',
    role: 'admin',
    username: 'hhassonp',
    contact: '(582) 516-1324',
    email: 'hhassonp@bizjournals.com',
    status: 'inactive',
  },
  {
    id: 27,
    fullName: 'Germain Jacombs',
    role: 'editor',
    username: 'gjacombsq',
    contact: '(137) 467-5393',
    email: 'gjacombsq@jigsy.com',
    status: 'active',
  },
  {
    id: 28,
    fullName: 'Bree Kilday',
    role: 'maintainer',
    username: 'bkildayr',
    contact: '(412) 476-0854',
    email: 'bkildayr@mashable.com',
    status: 'active',
  },
  {
    id: 29,
    fullName: 'Candice Pinyon',
    role: 'maintainer',
    username: 'cpinyons',
    contact: '(170) 683-1520',
    email: 'cpinyons@behance.net',
    status: 'active',
  },
  {
    id: 30,
    fullName: 'Isabel Mallindine',
    role: 'user',
    username: 'imallindinet',
    contact: '(332) 803-1983',
    email: 'imallindinet@shinystat.com',
    status: 'pending',
  },
  {
    id: 31,
    fullName: 'Gwendolyn Meineken',
    role: 'admin',
    username: 'gmeinekenu',
    contact: '(551) 379-7460',
    email: 'gmeinekenu@hc360.com',
    status: 'pending',
  },
  {
    id: 32,
    fullName: 'Rafaellle Snowball',
    role: 'editor',
    username: 'rsnowballv',
    contact: '(974) 829-0911',
    email: 'rsnowballv@indiegogo.com',
    status: 'pending',
  },
  {
    id: 33,
    fullName: 'Rochette Emer',
    role: 'admin',
    username: 'remerw',
    contact: '(841) 889-3339',
    email: 'remerw@blogtalkradio.com',
    status: 'active',
  },
  {
    id: 34,
    fullName: 'Ophelie Fibbens',
    role: 'user',
    username: 'ofibbensx',
    contact: '(764) 885-7351',
    email: 'ofibbensx@booking.com',
    status: 'active',
  },
  {
    id: 35,
    fullName: 'Stephen MacGilfoyle',
    role: 'maintainer',
    username: 'smacgilfoyley',
    contact: '(350) 589-8520',
    email: 'smacgilfoyley@bigcartel.com',
    status: 'pending',
  },
  {
    id: 36,
    fullName: 'Bradan Rosebotham',
    role: 'user',
    username: 'brosebothamz',
    contact: '(882) 933-2180',
    email: 'brosebothamz@tripadvisor.com',
    status: 'inactive',
  },
  {
    id: 37,
    fullName: 'Skip Hebblethwaite',
    role: 'admin',
    username: 'shebblethwaite10',
    contact: '(610) 343-1024',
    email: 'shebblethwaite10@arizona.edu',
    status: 'inactive',
  },
  {
    id: 38,
    fullName: 'Moritz Piccard',
    role: 'maintainer',
    username: 'mpiccard11',
    contact: '(365) 277-2986',
    email: 'mpiccard11@vimeo.com',
    status: 'inactive',
  },
  {
    id: 39,
    fullName: 'Tyne Widmore',
    role: 'user',
    username: 'twidmore12',
    contact: '(531) 731-0928',
    email: 'twidmore12@bravesites.com',
    status: 'pending',
  },
  {
    id: 40,
    fullName: 'Florenza Desporte',
    role: 'author',
    username: 'fdesporte13',
    contact: '(312) 104-2638',
    email: 'fdesporte13@omniture.com',
    status: 'active',
  },
  {
    id: 41,
    fullName: 'Edwina Baldetti',
    role: 'maintainer',
    username: 'ebaldetti14',
    contact: '(315) 329-3578',
    email: 'ebaldetti14@theguardian.com',
    status: 'pending',
  },
  {
    id: 42,
    fullName: 'Benedetto Rossiter',
    role: 'editor',
    username: 'brossiter15',
    contact: '(323) 175-6741',
    email: 'brossiter15@craigslist.org',
    status: 'inactive',
  },
  {
    id: 43,
    fullName: 'Micaela McNirlan',
    role: 'admin',
    username: 'mmcnirlan16',
    contact: '(242) 952-0916',
    email: 'mmcnirlan16@hc360.com',
    status: 'inactive',
  },
  {
    id: 44,
    fullName: 'Vladamir Koschek',
    role: 'author',
    username: 'vkoschek17',
    contact: '(531) 758-8335',
    email: 'vkoschek17@abc.net.au',
    status: 'active',
  },
  {
    id: 45,
    fullName: 'Corrie Perot',
    role: 'user',
    username: 'cperot18',
    contact: '(659) 385-6808',
    email: 'cperot18@goo.ne.jp',
    status: 'pending',
  },
  {
    id: 46,
    fullName: 'Saunder Offner',
    role: 'maintainer',
    username: 'soffner19',
    contact: '(200) 586-2264',
    email: 'soffner19@mac.com',
    status: 'pending',
  },
  {
    id: 47,
    fullName: 'Karena Courtliff',
    role: 'admin',
    username: 'kcourtliff1a',
    contact: '(478) 199-0020',
    email: 'kcourtliff1a@bbc.co.uk',
    status: 'active',
  },
  {
    id: 48,
    fullName: 'Onfre Wind',
    role: 'admin',
    username: 'owind1b',
    contact: '(344) 262-7270',
    email: 'owind1b@yandex.ru',
    status: 'pending',
  },
  {
    id: 49,
    fullName: 'Paulie Durber',
    role: 'user',
    username: 'pdurber1c',
    contact: '(694) 676-1275',
    email: 'pdurber1c@gov.uk',
    status: 'inactive',
  },
  {
    id: 50,
    fullName: 'Beverlie Krabbe',
    role: 'editor',
    username: 'bkrabbe1d',
    contact: '(397) 294-5153',
    email: 'bkrabbe1d@home.pl',
    status: 'active',
  }
] as any)
