const prefix = 'reports'

export const reportEndpoints = {
  salesSummary: `${prefix}/sales-summary`,
  dailySales: `${prefix}/daily-sales`,
  itemSales: `${prefix}/item-sales`,
  categorySales: `${prefix}/category-sales`,
  paymentMethods: `${prefix}/payment-methods`,
  customerSales: `${prefix}/customer-sales`,
  hourlySales: `${prefix}/hourly-sales`,
  discounts: `${prefix}/discounts`,
  taxes: `${prefix}/taxes`,
  refunds: `${prefix}/refunds`,
  branchWise: `${prefix}/branch-wise`,
  profit: `${prefix}/profit`,
  revenueTrend: `${prefix}/revenue-trend`,
  orderTypeBreakdown: `${prefix}/order-type-breakdown`,
  categoryPerformance: `${prefix}/category-performance`,
  topProducts: `${prefix}/top-products`,
  customerAnalytics: `${prefix}/customer-analytics`,
  recentOrders: `${prefix}/recent-orders`,
  inventoryInsights: `${prefix}/inventory-insights`,
  staffSales: `${prefix}/staff-sales`,
  orderType: `${prefix}/order-type`,
  inventoryConsumption: `${prefix}/inventory-consumption`,
  filterOptions: `${prefix}/filter-options`,
  groceryDashboardSummary: `grocery-reports/dashboard-summary`,
  groceryStockSummary: `grocery-reports/stock-summary`,
  groceryPurchaseReport: `grocery-reports/purchase-report`,
  groceryConsumptionReport: `grocery-reports/consumption-report`,
  groceryStockMovementReport: `grocery-reports/stock-movement-report`,
  groceryLowStockReport: `grocery-reports/low-stock-report`,
  groceryOutOfStockReport: `grocery-reports/out-of-stock-report`,
  groceryExpiryReport: `grocery-reports/expiry-report`,
  grocerySupplierReport: `grocery-reports/supplier-report`,
  groceryWastageReport: `grocery-reports/wastage-report`,
  groceryFoodCostReport: `grocery-reports/food-cost-report`,
  groceryInventoryValueReport: `grocery-reports/inventory-value-report`,
  groceryPurchaseTrend: `grocery-reports/purchase-trend`,
  groceryConsumptionTrend: `grocery-reports/consumption-trend`,
  groceryTopConsumedIngredients: `grocery-reports/top-consumed-ingredients`
}
